<a href="https://colab.research.google.com/github/Shreyask28/ml-python-tutorial/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Pandas Comprehensive Tutorial***

In [ ]:
print("introduction to python")

introduction to python

Key data structures in pandas

> series


> DataFrame

## Example of series

In [ ]:
import pandas as pd
s=pd.Series([1,2,3,4,5,6,])
print(s)
#the left side columns are labels of data
#the right side columns are data
##the series is labeled array unlike lists in python which are plain arrays
### it is one dimensional

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

## Example of dataframe

In [ ]:
import pandas as pd
df=pd.DataFrame({"names":["henry","rohan","shubham"],"marks":[10,25,67]})
df

# it is two dimensional

     names  marks
0    henry     10
1    rohan     25
2  shubham     67

Importing CSV,JSON,EXCEL FILES

In [ ]:
import pandas as pd
#csv
df=pd.read_csv("iris.csv")
df
#Json
df2=pd.read_json("iris.json")
df2
#excel
df3=pd.read_excel("iris.xlsx")
df3

### Importing files in colab notebook (example=json file)

In [ ]:
from google.colab import files
import pandas as pd

# 1. Run this cell to open the file picker and select 'iris.json' from your Mac
uploaded = files.upload()

# 2. Read the uploaded file into Pandas
df = pd.read_json('iris.json')
df

Saving iris.json to iris.json

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

# Analysing data

### viewing the data

One of the most used method for getting a quick overview of the DataFrame, is the head() method.

The head() method returns the headers and a specified number of rows, starting from the top.

In [ ]:
import pandas as pd
df =pd.read_json('iris.json')
df.head(10)
#prints first 10 elements of dataframe

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa
5          5.4         3.9          1.7         0.4  setosa
6          4.6         3.4          1.4         0.3  setosa
7          5.0         3.4          1.5         0.2  setosa
8          4.4         2.9          1.4         0.2  setosa
9          4.9         3.1          1.5         0.1  setosa

In [ ]:
import pandas as pd
df =pd.read_json('iris.json')
df.tail(10)
#prints last 10 elements of dataframe

     sepalLength  sepalWidth  petalLength  petalWidth    species
140          6.7         3.1          5.6         2.4  virginica
141          6.9         3.1          5.1         2.3  virginica
142          5.8         2.7          5.1         1.9  virginica
143          6.8         3.2          5.9         2.3  virginica
144          6.7         3.3          5.7         2.5  virginica
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

In [ ]:
import pandas as pd
df =pd.read_json('iris.json')
df.head()
#prints first 5 elements of dataframe if only head()

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

## Info About the Data

The DataFrames object has a method called info(), that gives you more information about the data set.

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sepalLength  150 non-null    float64
 1   sepalWidth   150 non-null    float64
 2   petalLength  150 non-null    float64
 3   petalWidth   150 non-null    float64
 4   species      150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None

# Pandas Comprehensive Tutorial

**Created by:** Shreyas Kumbhar
**GitHub:** [@Shreyask28](https://github.com/Shreyask28)  
**LinkedIn:** [Shreyas_Kumbhar](https://linkedin.com/in/shreyas-kumbhar-63715237a/)  
**Email:** kumbharshreyas7777@gmail.com

**note**:This notebook is introduction of Pandas for beginners and not contains advanced concepts in it.

---
*A step-by-step guide covering fundamental to advanced Pandas operations.*